#!/usr/bin/env bash
# Notify an external service that a successful deploy has occurred.

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

curl "https://0beac0346e14b146d60a1d277d4826f7.m.pipedream.net"